Add components to documentation site
gadgetfather/ManaUI pull request #13
Opened 2022-02-03 14:07 UTC by gadgetfather

I have added created components for the documentation site. Please review them. I have made all P0 and some of the P1 components
Link : https://mana-ui.netlify.app/
![image](https://user-images.githubusercontent.com/77927918/152358290-57659777-d2c1-436c-a071-ae6ec351116f.png)
![image](https://user-images.githubusercontent.com/77927918/152358388-0a3b9c37-93d1-4145-a7b9-0d786a04e602.png)
![image](https://user-images.githubusercontent.com/77927918/152358406-e58f84f3-7e52-4def-9faa-edd8a1c53352.png)

2022-02-03 14:21 UTC, b0llu approved these changes
Great and clean code!

2022-02-03 17:11 UTC, shaik-saad requested changes
Added some suggestion, do check them out

2022-02-03 17:11 UTC, shaik-saad commented on index.html
> +    <link rel="stylesheet" href="/style.css">
You can add a dot before the forward slash

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/utilities-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
button has a href here, you can remove it.

2022-02-03 17:11 UTC, shaik-saad commented on Components/list-component/list.css
> +    /* align-items: center; */
if not needed, you can remove this comment.

2022-02-03 17:11 UTC, shaik-saad commented on Components/card/card.css
> + flex-direction: row;
flex is by default row, you can remove this.

2022-02-03 17:11 UTC, shaik-saad commented on Components/list-component/list.css
> +    /* list-style: circle; */
if not needed you can remove this one.

2022-02-03 17:11 UTC, shaik-saad commented on Components/list-component/list.css
> +    flex-direction: row;
flex-direction: is by default row, so you can remove this line

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/alert-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
Button has a href attribute here

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/badge-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
href attribute here too.

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/button-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
href attribute here too.

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/card-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
href attribute here too

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/color-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
href here too

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/image-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
you can remove this href

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/index.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
href here too

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/input-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
button has a href

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/list-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
href

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/modal-page.html
> +                <button class="btn btn-secondary hamburger-menu" href="#"><i class="fas fa-bars"></i></button>
href here too

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/style.css
> +    /* border: 2px solid red; */
if not needed, you can remove this comment

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/style.css
> +    /* border: 1px solid gold; */
if not needed, you can remove this comment

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/style.css
> +}
if these lines are not needed, you can remove them

2022-02-03 17:11 UTC, shaik-saad commented on Documentation/style.css
> +    flex-direction: row;
it's by default row, so you can remove this line

2022-02-03 17:41 UTC, gadgetfather commented on Components/card/card.css
> + flex-direction: row;
No actually for card container, i had made it vertical, so to specifically make it horizontal i  gave flex direction row to

2022-02-03 18:07 UTC, VishalPatil18 approved these changes
- The installation code embed width is broken. You could fix that.
![Screenshot 2022-02-03 at 23 17 08](https://user-images.githubusercontent.com/62737267/152399677-5fa93729-a95e-49f2-b536-7f9a505d6006.png)

- The close buttons on the alerts could have a cursor of pointer when they're being hovered upon.

![Screenshot 2022-02-03 at 23 18 56](https://user-images.githubusercontent.com/62737267/152399703-a4da9362-0efc-487e-9b29-85b1b5e3aa59.png)

The rest looks good. Great stuff @gadgetfather

2022-02-04 04:02 UTC, shaik-saad approved these changes
Looks good Akshay! you can go ahead with merge.

2022-02-04 04:25 UTC, merged